# MonsterInc Example Configuration File
# Copy this to config.yaml and modify as needed

# Global application mode: "onetime" or "automated"
mode: "onetime"

# HTTPX tool configuration
httpx_runner_config:
  method: "GET"
  threads: 25
  timeout_secs: 10
  retries: 1
  follow_redirects: true
  max_redirects: 10
  verbose: false
  tech_detect: true
  extract_title: true
  extract_status_code: true
  extract_location: true
  extract_content_length: true
  extract_server_header: true
  extract_content_type: true
  extract_ips: true
  extract_asn: true
  extract_body: false
  extract_headers: true

# Web crawler settings
crawler_config:
  auto_add_seed_hostnames: true
  max_concurrent_requests: 10
  max_content_length_mb: 2
  max_depth: 5
  request_timeout_secs: 10
  
  scope:
    disallowed_hostnames: []
    disallowed_subdomains: []
    disallowed_file_extensions:
      - .css
      - .png
      - .jpg
      - .jpeg
      - .gif
      - .js
      - .ico
      - .svg
      - .ttf
      - .woff
      - .woff2
      - .mp3
      - .mp4
      - .wav

  # Auto-calibrate for skipping similar URLs
  auto_calibrate:
    enabled: true
    max_similar_urls: 1
    ignore_parameters: ["tid", "fid", "page", "id", "p", "offset", "limit"]
    auto_detect_locales: true
    enable_skip_logging: false

  # Headless browser (disabled by default)
  headless_browser:
    enabled: false
    window_width: 1920
    window_height: 1080
    page_load_timeout_secs: 60
    wait_after_load_ms: 1000
    disable_images: true
    ignore_https_errors: true
    pool_size: 3
    browser_args:
      - "--no-sandbox"
      - "--disable-dev-shm-usage"
      - "--disable-gpu"

  # URL normalization
  url_normalization:
    strip_fragments: true
    strip_tracking_params: true
    custom_strip_params:
      - "utm_source"
      - "utm_medium"
      - "utm_campaign"
      - "utm_content"
      - "utm_term"
      - "fbclid"
      - "gclid"
      - "ref"
      - "referrer"

  # Retry configuration
  retry_config:
    max_retries: 3
    base_delay_secs: 10
    max_delay_secs: 60
    enable_jitter: true
    retry_status_codes: [429]

# HTML report settings
reporter_config:
  output_dir: "reports/scan"
  items_per_page: 25
  embed_assets: true
  report_title: "MonsterInc Scan Report"
  enable_data_tables: true
  max_probe_results_per_report_file: 1000

# Data storage settings
storage_config:
  parquet_base_path: "database"
  compression_codec: "zstd"

# Discord notifications
notification_config:
  scan_service_discord_webhook_url: ""  # Add your webhook URL here
  notify_on_success: false
  notify_on_failure: false
  notify_on_scan_start: false
  notify_on_critical_error: true

# Logging configuration
log_config:
  log_level: "info"
  log_format: "console"
  log_file: "logs/monsterinc.log"
  max_log_size_mb: 100
  max_log_backups: 3
  use_subdirs: true

# Automated scan scheduler
scheduler_config:
  cycle_minutes: 10080  # 7 days
  retry_attempts: 2
  sqlite_db_path: "database/scheduler/scheduler_history.db"

# Batch processing for large scans
scan_batch_config:
  batch_size: 200
  max_concurrent_batch: 1
  batch_timeout_mins: 45
  threshold_size: 500