discord:
  token: ""  # Set via DISCORD_BOT_TOKEN environment variable
  guild_id: ""  # Your Discord server ID
  webhook_url: ""  # Set via DISCORD_WEBHOOK_URL environment variable

bot:
  rate_limit:
    commands_per_minute: 30
    burst_limit: 5
    window_duration: 1m
  logging:
    level: "info"
    format: "console"
    file: ""  # Optional: path to log file

paths:
  targets_dir: "../../targets"
  urls_file: "urls.txt"
  js_html_file: "js_html.txt"
  monsterinc_bin: "../../monsterinc"

service:
  check_timeout: 30s
  execute_timeout: 5m
  process_name: "monsterinc"
  watchdog_enabled: true 